#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'isaac-ros-navigation-goal','console_scripts','SetNavigationGoal'
__requires__ = 'isaac-ros-navigation-goal'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('isaac-ros-navigation-goal', 'console_scripts', 'SetNavigationGoal')()
    )
